#USE THE LATEST VERSION OF THE NODEJS IMAGE AS THE BASE IMAGE
FROM node:latest

#SET THE WORKING DIRECTRY
WORKDIR /usr/src/app

#COPY THE CONTENTS OF THE LOCAL "NODEAPP" DIRECTRY TO THE ROOT DIRECTRY
COPY nodeapp/* /

#RUN THE NPM INSTALL COMMAND
RUN npm install 

#Start the pplication
CMD ["npm" , "start"]